name: Nix

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      cachix_name:
        required: false
        type: string
        default: linuxmobile

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: ${{ inputs.cachix_name }}
      - run: ${{ inputs.command }}
